language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
sudo: false
addons:
  apt:
    sources:
    - avsm
    packages:
    - camlp4
    - camlp4-extra
    - m4
    - ocaml
    - ocaml-base
    - ocaml-base-nox
    - ocaml-compiler-libs
    - ocaml-native-compilers
    - ocaml-nox
    - time
    - aspcud

env:
  - FORK_USER=talex5 FORK_BRANCH=containers OPAMYES=true PACKAGE=core-lwt OCAML_VERSION=4.03.0 OPAM_SWITCH=$OCAML_VERSION TESTS=false
